---
abstract: 'wxSingleChoiceDialog with RadioBox'
author:
  - 'Tarek Unger <tu2@gmx.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wx-Perl-RadioBoxDialog
provides:
  Wx::Perl::RadioBoxDialog:
    file: lib/Wx/Perl/RadioBoxDialog.pm
    version: 0.01
requires:
  Wx: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/taunger/Config-Source
version: 0.01
